In [1]:
import torch
import numpy as np

In [15]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

In [7]:
print(f"The dimension: {scalar.ndim}, And the Scalar conversion: {scalar.item()}")

The dimension: 0, And the Scalar conversion: 7


In [13]:
rand_tens = torch.randint(low=2, high=10, size=(3,4), dtype=torch.int32)
rand_tens

tensor([[9, 4, 4, 4],
        [9, 4, 2, 7],
        [6, 2, 6, 2]], dtype=torch.int32)

In [30]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,  # defaults to None, which is torch.float32 or whatever datatype is passed
                            #    device='cuda',  # defaults to None, which uses the default tensor type
                               requires_grad=False)  # if True, operations performed on the tensor are recorded

torch.half is the same as torch.float16

In [22]:
float_32_tensor_2 = torch.tensor([3, 6, 8],
                               dtype=torch.half, requires_grad=False)

In [23]:
float_32_tensor_2

tensor([3., 6., 8.], device='cuda:0', dtype=torch.float16)

In [24]:
float_32_tensor_2 * 10

tensor([30., 60., 80.], device='cuda:0', dtype=torch.float16)

In [31]:
torch.matmul(float_32_tensor, float_32_tensor_2)

tensor(117., device='cuda:0', dtype=torch.float16)

In [36]:
%%time
# Tha bove can also be written as
float_32_tensor @ float_32_tensor_2

CPU times: total: 0 ns
Wall time: 2 ms


tensor(117., device='cuda:0', dtype=torch.float16)

In [45]:
tensor1 = torch.randint(12, (3,4))
tensor2 = torch.randint(14, (2, 4))

In [47]:
tensor1 @ tensor2.T

tensor([[182, 207],
        [248, 238],
        [270, 274]])

In [48]:
tensor_A = torch.tensor([[1., 2.],
                         [3., 4.],
                         [5., 6.]])

In [60]:
torch.manual_seed(42)
linear = torch.nn.Linear(2, 6)


In [61]:
output = linear(tensor_A)

In [57]:
output

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

In [66]:
print(float_32_tensor_2.type(torch.float32).mean())
print(torch.mean(float_32_tensor_2.type(torch.float32)))

tensor(5.6667, device='cuda:0')
tensor(5.6667, device='cuda:0')


In [68]:
output.argmax()

tensor(12)

In [69]:
tensor_B = torch.arange(1,8)

In [100]:
stacked = torch.stack([tensor_B, tensor_B], dim=1).T

In [123]:
torch.manual_seed(42)
tensor_2_7 = torch.randint(20, (2,7))
tensor_2_7

tensor([[ 2,  7, 16, 14,  6, 15,  0],
        [ 4, 10, 13, 18, 14, 10, 14]])

In [124]:
tensor_2_7[0,:] = tensor_2_7[-1,:]
tensor_2_7

tensor([[ 4, 10, 13, 18, 14, 10, 14],
        [ 4, 10, 13, 18, 14, 10, 14]])

In [105]:
stacked

tensor([1, 2, 3, 4, 5, 6, 7])

In [81]:
x_reshaped = tensor_B.reshape(1,7)

In [82]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7]])

In [87]:
x_squeezed = x_reshaped.squeeze(dim=0)

In [91]:
x_unsqueezed = x_squeezed.unsqueeze(1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7]]),
 torch.Size([7, 1]))

In [99]:
tensor_3d = torch.randint(25, (3,3,3))
tensor_3d,tensor_3d[:,:,0]

(tensor([[[19, 24, 11],
          [24, 20,  3],
          [22,  9, 15]],
 
         [[11, 10,  7],
          [15, 18,  3],
          [24, 21, 18]],
 
         [[ 1,  4, 21],
          [15, 13,  0],
          [ 1,  7, 14]]]),
 tensor([[19, 24, 22],
         [11, 15, 24],
         [ 1, 15,  1]]))

In [134]:
np_1 = np.arange(0,8)
np_2_tensor = torch.from_numpy(np_1)
np_2_tensor.type(torch.float16)

tensor([0., 1., 2., 3., 4., 5., 6., 7.], dtype=torch.float16)

In [21]:
torch.manual_seed(7)
rand_tensor = torch.randint(21, (1,1,1,10)).to(device)

torch.manual_seed(7)
rand_tensor_2 = torch.randint(21, (10,)).to(device)

In [8]:
rand_tensor, rand_tensor_2

(tensor([[[[12, 13, 13,  8,  1, 18, 20,  8, 10, 17]]]]),
 tensor([12, 13, 13,  8,  1, 18, 20,  8, 10, 17]))

In [10]:
torch.max(rand_tensor_2), rand_tensor.min()

(tensor(20), tensor(1))

In [11]:
rand_tensor @ rand_tensor_2

tensor([[[1724]]])

In [23]:
rand_tensor_2.cpu().numpy()

array([12, 13, 13,  8,  1, 18, 20,  8, 10, 17], dtype=int64)